#!/bin/sh
set -e

install -d -m0755 downloads

PIP_URL='http://pypi.python.org/packages/source/p/pip/pip-0.7.2.tar.gz'
PIP_URL_QUOTED="$(echo "$PIP_URL"|sed 's,/,%2F,g; s,:,%3A,')"

if [ ! -e "downloads/$PIP_URL_QUOTED" ]; then
    wget -q "$PIP_URL" -O "downloads/$PIP_URL_QUOTED"
fi

if [ ! -e bin/pip ]; then
  rm -rf pip-temp
  install -d -m0755 pip-temp

  find downloads \
    -mindepth 1 -maxdepth 1 \
    -name '*%2Fpip-*.tar.gz' \
    | sort -n \
    | tail -n 1 \
    | while read pip; do
    tar xzf "$pip" -C pip-temp
  done

  find pip-temp \
    -mindepth 1 -maxdepth 1 \
    -name 'pip-*' \
    | sort -n \
    | tail -n 1 \
    | while read dir; do

    # without --ignore-installed, pip will see the parts/bootstrap-pip
    # version of itself, which is not helpful
    PYTHONPATH="$dir" \
    python \
    -m pip.__init__ \
    --environment=virtual \
    install \
    --ignore-installed \
    --download-cache=downloads \
    pip
  done

  rm -rf pip-temp
  ln -sf virtual/bin bin
fi

./bin/pip install \
  --download-cache=downloads \
  --requirement=requirements.txt

# forbid setuptools from using the network because it'll try to use
# easy_install, and we really wanted pip; next line will fail if pip
# requirements.txt does not match setup.py requirements -- sucky but
# good enough for now
./virtual/bin/python setup.py develop \
    --allow-hosts None
